// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCVWTxtYyxvIdOh0LdpCmVUBw5I7wrgg',
    appId: '1:900971223216:android:14e472433804b192200375',
    messagingSenderId: '900971223216',
    projectId: 'project2-47f55',
    storageBucket: 'project2-47f55.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLulS3KRUMBe24wEXOhIYvWDOHCLEvqk',
    appId: '1:900971223216:web:25aeacd68867d498200375',
    messagingSenderId: '900971223216',
    projectId: 'project2-47f55',
    authDomain: 'project2-47f55.firebaseapp.com',
    storageBucket: 'project2-47f55.firebasestorage.app',
    measurementId: 'G-GFL3Y663RM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVoNrwmdS7HIcyngvFNw4y-LonIj0p8w',
    appId: '1:900971223216:ios:0448d1c730691dd6200375',
    messagingSenderId: '900971223216',
    projectId: 'project2-47f55',
    storageBucket: 'project2-47f55.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVoNrwmdS7HIcyngvFNw4y-LonIj0p8w',
    appId: '1:900971223216:ios:0448d1c730691dd6200375',
    messagingSenderId: '900971223216',
    projectId: 'project2-47f55',
    storageBucket: 'project2-47f55.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLulS3KRUMBe24wEXOhIYvWDOHCLEvqk',
    appId: '1:900971223216:web:5ef4fe9d52761435200375',
    messagingSenderId: '900971223216',
    projectId: 'project2-47f55',
    authDomain: 'project2-47f55.firebaseapp.com',
    storageBucket: 'project2-47f55.firebasestorage.app',
    measurementId: 'G-BB29Z4NMBL',
  );

}